pymysql.err.OperationalError: (1045, "Access denied for user 'roo'@'localhost' (using password: YES)")
TypeError: Connection.__init__() got an unexpected keyword argument 'd'
folder "mysqlconnection.py" was spelled "MySQLconnection.py" 